COMMON_INDIAN_NAME_SUFFIXES = [
    "KUMAR", "KUMARI", "SINGH", "SHARMA", "YADAV", 
    "PATEL", "GUPTA", "CHAUDHARY", "PRASAD", "DEVI", 
    "REDDY", "RAO", "DAS", "CHANDRA", "NATH"
]

SPECIFIC_NAME_REPLACEMENTS = {}
